footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
  type: "circular"
  radius: 0.34 # for type "circular"
  line_start: [-0.3, 0.0] # for type "line"
  line_end: [0.3, 0.0] # for type "line"
  front_offset: 0.2 # for type "two_circles"
  front_radius: 0.2 # for type "two_circles"
  rear_offset: 0.2 # for type "two_circles"
  rear_radius: 0.2 # for type "two_circles"
  vertices: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]] # for type "polygon"
