publish_frequency: 2.0
update_frequency: 5.0
width: 15.0
height: 15.0
resolution: 0.1
global_frame: map
robot_base_frame: base_link
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.325, -0.325]]
footprint_padding: 0.05
rolling_window: true
static_map: false
transform_tolerance: 0.5
plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  # - {name: inflater, type: "costmap_2d::InflationLayer"}
