local_costmap:
  publish_frequency: 2.0
  update_frequency: 5.0
  width: 15.0
  height: 15.0
  resolution: 0.1
  origin_x: 0.0
  origin_y: 0.0
  global_frame: odom
  robot_base_frame: base_link
  footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.325, -0.325]]
  footprint_padding: 0.05
  rolling_window: true
  static_map: false
  width: 5.5
  height: 5.5
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,   type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
      #- {name: inflater, type: "costmap_2d::InflationLayer"}
  obstacles:
    observation_sources: /scan
    /scan: {data_type: LaserScan, sensor_frame: base_laser_link, expected_update_rate: 0.3, marking: true, clearing: true}
    footprint_clearing_enabled: false
  inflater:
    inflation_radius: 0.4
