## Robot Configuration Parameters
acc_lim_x: 0.2
acc_lim_theta: 0.2
max_vel_x: 0.55
max_vel_x_backwards: 0.2
max_vel_theta: 1.0
# The following parameters are relevant only for carlike robots:
min_turning_radius: 0.0
wheelbase: 1.0
cmd_angle_instead_rotvel: false
# The following parameters are relevant only for holonomic robots: New in ROS kinetic
max_vel_y: 0.55
acc_lim_y: 0.2
# The following parameters are relevant for the footprint model used for optimization (see Tutorial Obstacle Avoidance and Robot Footprint Model. New in version 0.3
footprint_model:
  type: "circular"
  radius: 0.3

## Goal Tolerance Parameters
xy_goal_tolerance: 0.2
yaw_goal_tolerance: 0.1
free_goal_vel: false

## Trajectory Configuration Parameters
dt_ref: 0.3
dt_hysteresis: 0.1
min_samples : 3
global_plan_overwrite_orientation: true
global_plan_viapoint_sep: 0.1
max_global_plan_lookahead_dist: 3.0
force_reinit_new_goal_dist: 1.0
feasibility_check_no_poses : 4
publish_feedback: false
shrink_horizon_backup: true
allow_init_with_backwards_motion: true
exact_arc_length: false
shrink_horizon_min_duration: 10.0

## Obstacle Parameters
min_obstacle_dist: 0.1
include_costmap_obstacles: true
costmap_obstacles_behind_robot_dist: 1.0
obstacle_poses_affected : 30
inflation_dist: 0.1
include_dynamic_obstacles: false
legacy_obstacle_association: false
obstacle_association_force_inclusion_factor: 1.5
obstacle_association_cutoff_factor: 5
# The following parameters are relevant only if costmap_converter plugins are desired (see tutorial):
costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
costmap_converter/CostmapToLinesDBSRANSAC:
    cluster_max_distance: 0.8
    cluster_min_pts: 2
    ransac_inlier_distance: 0.15
    ransac_min_inliers: 10
    ransac_no_iterations: 1500
    ransac_remainig_outliers: 3
    ransac_convert_outlier_pts: True
    ransac_filter_remaining_outlier_pts: False
    convex_hull_min_pt_separation: 0.1
costmap_converter_spin_thread: true
costmap_converter_rate: 5.0

## Optimization Parameters
no_inner_iterations : 5
no_outer_iterations : 4
penalty_epsilon: 0.01
weight_acc_lim_theta: 1.0
weight_acc_lim_x: 1.0
weight_acc_lim_y: 1.0
weight_adapt_factor: 2.0
weight_dynamic_obstacle: 50.0
weight_dynamic_obstacle_inflation: 0.1
weight_inflation: 0.1
weight_kinematics_forward_drive: 1.0
weight_kinematics_nh: 1.0
weight_kinematics_turning_radius: 0.0
weight_max_vel_theta: 1.0
weight_max_vel_x: 2.0
weight_max_vel_y: 2.0
weight_obstacle: 50.0
weight_optimaltime: 1.0
weight_viapoint: 0.0
weight_social_lookathuman: 1.0
weight_shortest_path: 1.0

## Parallel Planning in distinctive Topologies
enable_homotopy_class_planning: false
enable_multithreading: true
max_number_classes : 4
selection_cost_hysteresis: 1.0
selection_obst_cost_scale: 100.0
selection_viapoint_cost_scale: 1.0
selection_alternative_time_cost: false
roadmap_graph_no_samples : 15
roadmap_graph_area_width: 6
h_signature_prescaler: 1.0
h_signature_threshold: 0.1
obstacle_heading_threshold: 1.0
visualize_hc_graph: false
viapoints_all_candidates: true
switching_blocking_period: 0.0

## Miscellaneous Parameters
odom_topic: "/naoqi_driver_node/odom"
map_frame: "odom"

##Planner type
planner_type: 1

use_social_teb: true
